-- Script para adicionar serviços à tabela services
-- Execute este script no SQL Editor do Supabase ou em sua ferramenta de gerenciamento de banco de dados

INSERT INTO services (name) VALUES
('Consultoria Jurídica Preventiva'),
('Elaboração de Pareceres Jurídicos'),
('Due Diligence Legal'),
('Recuperação Judicial e Falência (Consultoria e Representação)'),
('Mediação e Arbitragem'),
('Compliance e LGPD (Consultoria e Implementação)'),
('Assessoria em Fusões e Aquisições (M&A)'),
('Serviços de Paralegal'),
('Certificação Digital (Emissão e Suporte)'),
('Perícia Contábil'),
('Consultoria em Controladoria'),
('Auditoria Interna'),
('Gestão de Custos'),
('Valuation (Avaliação de Empresas)'),
('Consultoria em Viabilidade Financeira'),
('Reestruturação Financeira de Empresas'),
('Criação de Apresentações Corporativas'),
('Edição de Imagens Profissionais'),
('Ilustração Digital'),
('Animação Gráfica / Motion Design'),
('UI/UX Design (Design de Interface e Experiência do Usuário)'),
('Testes de Usabilidade em Websites/Aplicativos'),
('Desenvolvimento de Aplicativos Nativos (iOS e Android)'),
('Desenvolvimento de PWA (Progressive Web Apps)'),
('Manutenção e Atualização de Websites'),
('Otimização de Performance de Sites (Velocidade)'),
('Consultoria em Marketing de Conteúdo'),
('Estratégia de Inbound Marketing'),
('Marketing de Afiliados (Consultoria)'),
('Automação de Marketing'),
('E-mail Marketing (Estratégia e Gestão)'),
('Marketing de Influência'),
('Assessoria de Comunicação Estratégica'),
('Gestão de Crise de Imagem'),
('Monitoramento de Marca Online'),
('Venda de Imóveis na Planta'),
('Venda de Imóveis de Luxo'),
('Administração de Bens Imóveis (Aluguéis)'),
('Consultoria para Compra do Primeiro Imóvel'),
('Consórcio Imobiliário (Venda e Assessoria)'),
('Seguro de Vida Resgatável'),
('Previdência Privada'),
('Seguro Viagem'),
('Seguro para Equipamentos Portáteis'),
('Seguro Garantia'),
('Seguro de Responsabilidade Civil Profissional'),
('Consultoria em Benefícios para Empresas (Saúde, Odonto, Vida)'),
('Análise Comportamental (DISC, MBTI)'),
('Orientação Profissional / Vocacional'),
('Desenvolvimento de Habilidades de Liderança'),
('Treinamento em Oratória / Falar em Público'),
('Consultoria em Ergonomia Postural'),
('Fisioterapia Esportiva'),
('Fisioterapia Dermatofuncional'),
('Drenagem Linfática'),
('Massagem Relaxante / Terapêutica'),
('Harmonização Orofacial (Botox, Preenchimento)'),
('Lentes de Contato Dentais'),
('Cirurgia Bucomaxilofacial'),
('Clínica Geral (Medicina)'),
('Cardiologia'),
('Dermatologia'),
('Ginecologia'),
('Pediatria'),
('Ortopedia'),
('Oftalmologia'),
('Otorrinolaringologia'),
('Urologia'),
('Endocrinologia'),
('Geriatria'),
('Nutrologia'),
('Pneumologia'),
('Reumatologia'),
('Neurologia'),
('Psiquiatria'),
('Oncologia'),
('Anestesiologia'),
('Radiologia / Diagnóstico por Imagem'),
('Patologia Clínica (Análises Laboratoriais)'),
('Medicina Veterinária Preventiva'),
('Acupuntura Veterinária'),
('Odontologia Veterinária'),
('Oftalmologia Veterinária'),
('Oncologia Veterinária'),
('Ortopedia Veterinária'),
('Cirurgia Veterinária Especializada'),
('Consultoria em Projetos Estruturais (Engenharia Civil)'),
('Consultoria em Projetos Hidráulicos'),
('Consultoria em Projetos Elétricos de Alta Tensão'),
('Projetos de Sistemas de Incêndio'),
('Consultoria em Eficiência Energética'),
('Projetos de Automação Industrial'),
('Consultoria em Gestão da Produção'),
('Consultoria em Logística Empresarial'),
('Projetos de Design de Mobiliário'),
('Consultoria em Luminotécnica'),
('Gestão de Resíduos da Construção Civil'),
('Laudos Técnicos (Engenharia, Arquitetura)'),
('Regularização de Imóveis'),
('Vistoria Cautelar de Imóveis'),
('Fotografia Imobiliária'),
('Tour Virtual de Imóveis'),
('Filmagem Corporativa'),
('Produção de Vídeos de Treinamento'),
('Transmissão de Eventos Online (Live Streaming)'),
('Edição de Áudio e Podcast'),
('Criação de Vinhetas e Jingles'),
('Serviços de Duplicação e Cópia de Chaves'),
('Instalação e Manutenção de Fechaduras Eletrônicas'),
('Confecção de Carimbos'),
('Serviços de Despachante Aduaneiro (Importação/Exportação)'),
('Certificado de Origem'),
('Consultoria em Legislação Aduaneira'),
('Freight Forwarding (Agenciamento de Cargas)'),
('Serviços de Trading Company'),
('Consultoria em Internacionalização de Empresas'),
('Consórcio Automotivo (Venda e Assessoria)'),
('Consórcio de Serviços'),
('Refinanciamento de Imóveis / Veículos'),
('Empréstimo Consignado'),
('Câmbio para Viagem Internacional'),
('Transferências Internacionais'),
('Fabricação de Joias Sob Encomenda'),
('Reparo de Relógios de Alta Complexidade'),
('Adaptação de Lentes de Contato Especiais'),
('Consultoria de Moda e Estilo'),
('Personal Shopper'),
('Conserto e Customização de Roupas'),
('Higienização de Estofados e Carpetes'),
('Impermeabilização de Tecidos'),
('Manutenção de Piscinas'),
('Instalação e Manutenção de Aquecedores de Água'),
('Serviços de Marido de Aluguel'),
('Montagem e Desmontagem de Móveis'),
('Limpeza Pós-Obra'),
('Limpeza de Fachadas'),
('Instalação de Redes de Proteção'),
('Manutenção de Telhados'),
('Impermeabilização de Lajes e Paredes'),
('Controle de Pombos'),
('Manejo de Pragas Urbanas'),
('Jardinagem (Manutenção, Projetos)'),
('Poda de Árvores'),
('Instalação de Sistemas de Irrigação'),
('Manutenção de Áreas Verdes Corporativas'),
('Fornecimento de Água Potável (Caminhão Pipa)'),
('Aluguel de Banheiros Químicos'),
('Serviços de Coleta Seletiva'),
('Destinação de Resíduos Industriais'),
('Consultoria em Gestão Ambiental'),
('Elaboração de Laudos Ambientais'),
('Licenciamento Ambiental'),
('Projetos de Eficiência Hídrica'),
('Instalação de Sistemas de Captação de Água da Chuva'),
('Consultoria em Segurança Alimentar (APPCC)'),
('Treinamento em Boas Práticas de Fabricação (BPF)'),
('Certificação ISO 22000 (Segurança Alimentar)'),
('Criação de Cardápios Nutricionais para Empresas/Escolas'),
('Serviço de Cozinha Industrial / Refeições Coletivas'),
('Fornecimento de Cestas Básicas'),
('Venda de Produtos Orgânicos Certificados'),
('Entrega de Refeições Saudáveis (Marmitas Fitness)'),
('Consultoria para Abertura de Franquias (para Franqueadores)'),
('Consultoria para Aquisição de Franquias (para Franqueados)'),
('Avaliação de Potencial de Franqueabilidade'),
('Desenvolvimento de Circular de Oferta de Franquia (COF)'),
('Consultoria em Expansão de Redes de Franquias'),
('Treinamento para Franqueados'),
('Auditoria em Unidades Franqueadas'),
('Consultoria em Sucessão Familiar em Empresas'),
('Governança Corporativa (Consultoria)'),
('Mapeamento e Otimização de Processos de Negócio'),
('Implementação de Metodologias Ágeis (Scrum, Kanban)'),
('Gerenciamento de Projetos (Metodologias PMI, etc.)'),
('Consultoria em Lean Manufacturing'),
('Otimização da Cadeia de Suprimentos (Supply Chain)'),
('Consultoria em Customer Experience (Experiência do Cliente)'),
('Implementação de Programas de Fidelidade'),
('Pesquisa de Satisfação de Clientes'),
('Mapeamento de Jornada do Cliente'),
('Treinamento em Atendimento ao Cliente'),
('Desenvolvimento de Manuais de Marca'),
('Gestão de Redes de Franquias (para Franqueador)'),
('Criação de Campanhas Publicitárias Offline (TV, Rádio, Revista)'),
('Planejamento de Mídia (Offline e Online)'),
('Compra de Espaço Publicitário'),
('Produção de Jingles e Spots de Rádio'),
('Produção de Comerciais de TV'),
('Marketing Sensorial (Olfativo, Auditivo, Tátil)'),
('Instalação e Manutenção de Sistemas de Som Ambiente'),
('Design de Embalagens'),
('Rotulagem de Produtos'),
('Consultoria em Ponto de Venda (PDV)'),
('Merchandising em Lojas'),
('Organização de Vitrines'),
('Treinamento para Vendedores (Técnicas de Venda)'),
('Workshop de Negociação'),
('Consultoria em Formação de Preços'),
('Gestão de Equipes de Vendas'),
('Coaching para Vendedores de Alta Performance'),
('Desenvolvimento de Planos de Incentivo para Vendas'),
('Pesquisa Salarial e de Benefícios'),
('Avaliação Psicológica para Seleção'),
('Programas de Qualidade de Vida no Trabalho (QVRT)'),
('Ginástica Laboral Online'),
('Consultoria em Desenvolvimento Organizacional'),
('Planejamento Estratégico de RH'),
('Mentoria para Executivos'),
('Outplacement (Apoio a Profissionais Desligados)'),
('Gestão de Cargos e Salários'),
('Implementação de Plano de Carreira'),
('Pesquisa de Clima Organizacional'),
('Desenvolvimento de Código de Conduta e Ética'),
('Treinamento em Compliance'),
('Treinamento em Prevenção de Assédio'),
('Consultoria em Diversidade e Inclusão'),
('Programas de Voluntariado Corporativo'),
('Elaboração de Relatórios de Sustentabilidade (GRI)'),
('Consultoria em Responsabilidade Social Corporativa'),
('Projetos de Captação de Recursos (ONGs, Projetos Sociais)'),
('Elaboração de Projetos Culturais (Lei Rouanet, etc.)'),
('Produção Executiva de Projetos Culturais'),
('Organização de Exposições e Mostras'),
('Curadoria de Arte'),
('Avaliação de Obras de Arte para Seguro/Patrimônio'),
('Leilões de Arte e Antiguidades'),
('Restauração de Livros Antigos'),
('Encadernação Artística'),
('Conservação de Acervos (Bibliotecas, Arquivos)'),
('Digitalização de Documentos e Acervos'),
('Gestão Eletrônica de Documentos (GED)'),
('Serviços de Arquivologia'),
('Consultoria em Organização de Arquivos Físicos'),
('Certificação Digital (Pessoa Física e Jurídica)'),
('Consultoria em Segurança da Informação'),
('Testes de Invasão (Pentest)'),
('Recuperação de Dados'),
('Perícia Forense Computacional'),
('Consultoria em Proteção de Dados (LGPD)'),
('Treinamento em Conscientização de Segurança da Informação'),
('Monitoramento de Rede e Servidores'),
('Gerenciamento de Backups'),
('Serviços de Cloud Computing (Migração, Gestão)'),
('Suporte Técnico Especializado (Sistemas Operacionais, Redes)'),
('Aluguel de Equipamentos de TI'),
('Manutenção de Impressoras e Copiadoras'),
('Suporte Técnico Remoto (Help Desk)'),
('Instalação de Softwares e Aplicativos'),
('Desenvolvimento de Dashboards e Relatórios (BI)'),
('Análise de Dados'),
('Consultoria em Big Data'),
('Machine Learning (Desenvolvimento e Consultoria)'),
('Inteligência Artificial (Consultoria em Aplicações)'),
('Consultoria em Criptomoedas e Blockchain'),
('Desenvolvimento de Smart Contracts'),
('Consultoria em Tokenização de Ativos'),
('Serviços de Notarização Digital'),
('Consultoria em Proteção de Marca e Patentes'),
('Registro de Marcas e Patentes no INPI'),
('Monitoramento de Uso Indevido de Marca'),
('Assessoria Jurídica para Startups'),
('Elaboração de Termos de Uso e Política de Privacidade'),
('Consultoria em Modelagem de Negócios'),
('Elaboração de Plano de Negócios'),
('Consultoria em Captação de Investimentos (Anjos, VCs)'),
('Pitch Deck (Criação e Consultoria)'),
('Mentoria para Empreendedores'),
('Aceleradora de Startups (Serviços)'),
('Incubadora de Empresas (Serviços)'),
('Coworking Space (Serviços de Escritório Compartilhado)'),
('Escritório Virtual (Endereço Comercial, Atendimento Telefônico)'),
('Serviços de Secretariado Remoto'),
('Assistente Virtual'),
('Serviços de Concierge Corporativo'),
('Organização de Viagens Corporativas (Detalhado)'),
('Gestão de Despesas de Viagem'),
('Consultoria em Etiqueta Corporativa'),
('Treinamento em Atendimento Telefônico Profissional');
