-- Script para adicionar a segunda parte dos serviços à tabela services
-- Execute este script no SQL Editor do Supabase após executar o primeiro script

INSERT INTO services (name) VALUES
('Serviços de Call Center Terceirizado'),
('SAC - Serviço de Atendimento ao Cliente (Terceirizado)'),
('Ouvidoria (Terceirizada)'),
('Pesquisa de Mercado Qualitativa (Grupos Focais)'),
('Pesquisa de Mercado Quantitativa (Questionários)'),
('Análise da Concorrência'),
('Inteligência de Mercado'),
('Geomarketing (Análise de Localização e Mercado)'),
('Consultoria em Expansão Geográfica de Negócios'),
('Serviços de Auditoria de Lojas (Cliente Oculto)'),
('Treinamento em Merchandising para Equipes de Loja'),
('Otimização de Layout de Lojas'),
('Consultoria em Gestão de Estoque'),
('Otimização de Processos de Venda (Funil de Vendas)'),
('Implementação de CRM de Vendas'),
('Coaching para Líderes de Vendas'),
('Treinamento em Fechamento de Vendas'),
('Serviços de Pós-Venda e Sucesso do Cliente'),
('Gestão de Comunidades Online'),
('Criação e Gestão de Fóruns Online'),
('Moderação de Conteúdo Online'),
('Gestão de Reputação Online'),
('Monitoramento de Redes Sociais para Crises'),
('Criação de Chatbots para Atendimento'),
('Automação de Atendimento ao Cliente'),
('Consultoria em Experiência do Usuário (UX) em Produtos/Serviços'),
('Design Thinking (Facilitação e Consultoria)'),
('Inovação em Produtos e Serviços (Consultoria)'),
('Prototipagem Rápida'),
('Testes A/B para Websites e Campanhas'),
('Análise de Métricas e Indicadores de Performance (KPIs)'),
('Criação de Dashboards Gerenciais'),
('Consultoria em Otimização de Processos Financeiros'),
('Gestão de Fluxo de Caixa'),
('Contas a Pagar e a Receber (Terceirizado)'),
('Conciliação Bancária'),
('Faturamento (Emissão de Notas Fiscais - Terceirizado)'),
('Cobrança (Serviços de Cobrança)'),
('Análise de Crédito'),
('Consultoria em Recuperação de Crédito'),
('Assessoria em Renegociação de Dívidas (Empresas)'),
('Planejamento Tributário para Pessoas Físicas'),
('Consultoria em Investimentos Internacionais'),
('Gestão de Patrimônio (Wealth Management)'),
('Assessoria em Compra e Venda de Ativos (Ouro, Prata, etc.)'),
('Consultoria em Criptoativos para Investimento'),
('Planejamento de Aposentadoria Internacional'),
('Seguro de Vida para Planejamento Sucessório'),
('Seguro Garantia para Licitações'),
('Seguro de Riscos de Engenharia'),
('Seguro para Eventos'),
('Seguro para Transporte de Cargas'),
('Seguro de Crédito'),
('Seguro Fiança (Aluguel)'),
('Terapia Cognitivo-Comportamental (TCC)'),
('Terapia de Aceitação e Compromisso (ACT)'),
('Terapia EMDR'),
('Análise do Comportamento Aplicada (ABA)'),
('Psicanálise'),
('Terapia Reichiana'),
('Bioenergética'),
('Constelação Sistêmica (Individual e Organizacional)'),
('Hipnose Clínica'),
('Coaching de Performance'),
('Coaching de Relacionamento'),
('Coaching Financeiro'),
('Coaching de Saúde e Bem-Estar'),
('Consultoria em Mindfulness e Meditação'),
('Treinamento em Redução de Estresse'),
('Programas de Qualidade do Sono'),
('Consultoria em Nutrição Esportiva'),
('Elaboração de Dietas para Condições Específicas (Diabetes, Hipertensão)'),
('Nutrição Clínica (Atendimento em Consultório)'),
('Nutrição Funcional'),
('Fitoterapia (Prescrição e Acompanhamento)'),
('Aulas de Culinária Saudável'),
('Personal Chef (Serviços em Domicílio)'),
('Consultoria para Restaurantes (Elaboração de Cardápio, Ficha Técnica)'),
('Auditoria de Boas Práticas em Serviços de Alimentação'),
('Treinamento para Manipuladores de Alimentos'),
('Consultoria em Vigilância Sanitária para Negócios de Alimentação'),
('Fisioterapia Respiratória'),
('Fisioterapia Neurológica'),
('Fisioterapia Pediátrica'),
('RPG - Reeducação Postural Global'),
('Pilates Clínico'),
('Acupuntura Estética'),
('Acupuntura para Controle da Dor'),
('Acupuntura para Tratamento de Vícios'),
('Auriculoterapia'),
('Ventosaterapia'),
('Ozonioterapia (Consultoria sobre aplicações)'),
('Terapia Floral (Sessões e Prescrição)'),
('Aromaterapia Clínica'),
('Massagem Desportiva'),
('Massagem Shiatsu'),
('Reflexologia Podal'),
('Drenagem Linfática Manual'),
('Vacinação Humana (Serviços em Clínica)'),
('Enfermagem Domiciliar (Home Care)'),
('Cuidador de Idosos'),
('Fonoaudiologia (Adulto e Infantil)'),
('Terapia Ocupacional'),
('Pedagogia (Acompanhamento Pedagógico)'),
('Psicopedagogia'),
('AEE - Atendimento Educacional Especializado'),
('Inclusão Escolar (Consultoria)'),
('Desenvolvimento de Materiais Didáticos'),
('Treinamento para Professores'),
('Cursos Livres e Workshops'),
('Treinamento Corporativo Online (EAD)'),
('Criação de Conteúdo para EAD'),
('Plataformas de EAD (Consultoria e Implementação)'),
('Gamificação em Treinamento'),
('Consultoria em Cultura Organizacional'),
('Employer Branding (Marca Empregadora)'),
('Pesquisa de Engajamento de Funcionários'),
('Programas de Mentoria Interna'),
('Gestão de Voluntariado Corporativo'),
('Consultoria em Recrutamento por Competências'),
('Entrevistas por Competências'),
('Dinâmicas de Grupo para Seleção'),
('Avaliação Psicológica Online'),
('Testes Comportamentais para Seleção'),
('Onboarding (Processo de Integração de Novos Funcionários)'),
('Desligamento Humanizado (Outplacement)'),
('Consultoria em Relações Sindicais'),
('Negociação Sindical'),
('Elaboração de Acordos e Convenções Coletivas'),
('Compliance Trabalhista'),
('Auditoria Trabalhista'),
('Treinamento em Normas Regulamentadoras (NRs)'),
('Elaboração de PPRA e PCMSO'),
('CIPA (Constituição e Treinamento)'),
('Brigada de Incêndio (Formação e Treinamento)'),
('Consultoria em Prevenção e Combate a Incêndio'),
('Elaboração de Planos de Emergência'),
('Laudos de Insalubridade e Periculosidade'),
('Perícia Técnica Trabalhista'),
('Consultoria em Saúde e Segurança do Trabalho (SST)'),
('Gestão de Afastamentos e Benefícios Previdenciários'),
('eSocial (Consultoria e Implementação)'),
('Consultoria em Benefícios Flexíveis'),
('Gestão de Vale-Transporte e Vale-Refeição'),
('Programa de Participação nos Lucros e Resultados (PLR)'),
('Criação de Planos de Remuneração Variável'),
('Consultoria em Remuneração Estratégica'),
('Pesquisa de Remuneração de Mercado'),
('Design Organizacional'),
('Mapeamento de Funções e Competências'),
('Avaliação 360 Graus'),
('Planos de Desenvolvimento Individual (PDI)'),
('Coaching Executivo'),
('Mentoria para Lideranças'),
('Treinamento em Comunicação Assertiva'),
('Workshop de Feedback Construtivo'),
('Desenvolvimento de Habilidades de Resolução de Conflitos'),
('Negociação Estratégica (Treinamento)'),
('Design de Processos Seletivos Criativos'),
('Recrutamento por Indicação'),
('Hunting de Profissionais Raros'),
('Consultoria em Employer Branding Digital'),
('Gestão de Candidatos (Candidate Relationship Management - CRM)'),
('Automação de Processos de RH'),
('Sistemas de RH (Implementação e Suporte)'),
('People Analytics (Análise de Dados de RH)'),
('Consultoria em Cultura de Inovação'),
('Workshops de Brainstorming e Ideação'),
('Gerenciamento de Projetos de Inovação'),
('Consultoria em Design Thinking'),
('Facilitação de Workshops e Reuniões'),
('Mediação de Conflitos em Equipes'),
('Treinamento em Team Building'),
('Coaching de Equipe'),
('Consultoria em Comunicação Não Violenta (CNV)'),
('Treinamento em Resiliência'),
('Programas de Desenvolvimento de Liderança Feminina'),
('Consultoria em Inclusão de Pessoas com Deficiência'),
('Programas de Mentoria Reversa'),
('Consultoria em Sustentabilidade Corporativa (Detalhado)'),
('Elaboração de Inventários de Gases de Efeito Estufa (GEE)'),
('Consultoria em Ecoinovação'),
('Projetos de Energia Renovável (Consultoria)'),
('Certificação Ambiental (ISO 14001)'),
('Consultoria em Responsabilidade Social Empresarial'),
('Projetos de Investimento Social Privado'),
('Voluntariado Empresarial (Organização de Programas)'),
('Elaboração de Balanço Social'),
('Consultoria em Ética Empresarial'),
('Canais de Denúncia (Implementação e Gestão)'),
('Programas de Integridade e Compliance'),
('Auditoria de Fornecedores (Aspectos Sociais e Ambientais)'),
('Consultoria em Cadeia de Suprimentos Sustentável'),
('Treinamento em Compras Sustentáveis'),
('Logística Reversa (Consultoria)'),
('Gestão de Resíduos Eletrônicos'),
('Certificação de Produtos Sustentáveis'),
('Marketing Verde'),
('Comunicação de Sustentabilidade'),
('Elaboração de Relatórios Integrados'),
('Consultoria em Finanças Sustentáveis'),
('Investimentos de Impacto Social e Ambiental'),
('Consultoria em Negócios Sociais'),
('Economia Circular (Consultoria)'),
('Avaliação de Impacto Social'),
('Consultoria para Terceiro Setor (ONGs, Associações)'),
('Captação de Recursos para Projetos Sociais'),
('Elaboração de Projetos para Editais Públicos/Privados'),
('Gestão de Projetos Sociais'),
('Monitoramento e Avaliação de Projetos Sociais'),
('Treinamento para Voluntários'),
('Consultoria em Governança para ONGs');
