-- Script para adicionar especialidades à tabela specialties
-- Execute este script no SQL Editor do Supabase

INSERT INTO specialties (name) VALUES
('Advogado (Civil)'),
('Advogado (Empresarial)'),
('Advogado (Tributário)'),
('Advogado (Família)'),
('Advogado (Trabalhista)'),
('Advogado (Imobiliário)'),
('Advogado (Criminal)'),
('Advogado (Propriedade Intelectual)'),
('Advogado (Direito Digital)'),
('Advogado (Direito do Consumidor)'),
('Contador'),
('Consultor Financeiro'),
('Planejador Financeiro Pessoal'),
('Consultor de Investimentos'),
('Auditor'),
('Designer Gráfico'),
('Web Designer'),
('Desenvolvedor Front-end'),
('Desenvolvedor Back-end'),
('Desenvolvedor Full-stack'),
('Desenvolvedor Mobile (iOS)'),
('Desenvolvedor Mobile (Android)'),
('Consultor de Marketing Digital'),
('Especialista em SEO (Otimização para Mecanismos de Busca)'),
('Especialista em Mídias Sociais'),
('Gerente de Tráfego Pago (Google Ads, Meta Ads)'),
('Copywriter'),
('Produtor de Conteúdo (Texto/Blog)'),
('Produtor de Conteúdo (Vídeo)'),
('Produtor de Podcast'),
('Assessor de Imprensa / Relações Públicas'),
('Corretor de Imóveis (Residencial)'),
('Corretor de Imóveis (Comercial)'),
('Avaliador de Imóveis'),
('Administrador de Imóveis / Condomínios'),
('Seguros (Vida)'),
('Seguros (Saúde)'),
('Seguros (Automóvel)'),
('Seguros (Patrimonial/Empresarial)'),
('Seguros (Responsabilidade Civil)'),
('Corretor de Seguros'),
('Terapeuta (Psicólogo)'),
('Terapeuta (Coach de Vida)'),
('Terapeuta (Coach de Negócios)'),
('Nutricionista'),
('Personal Trainer'),
('Fisioterapeuta'),
('Quiropraxista'),
('Odontólogo (Clínico Geral)'),
('Odontólogo (Ortodontista)'),
('Odontólogo (Implantodontista)'),
('Médico (diversas especialidades)'),
('Veterinário'),
('Engenheiro Civil'),
('Engenheiro Eletricista'),
('Engenheiro Mecânico'),
('Engenheiro de Produção'),
('Engenheiro Ambiental'),
('Engenheiro de Segurança do Trabalho'),
('Arquiteto'),
('Designer de Interiores'),
('Paisagista'),
('Construtor / Empreiteiro'),
('Mestre de Obras'),
('Fotógrafo (Eventos)'),
('Fotógrafo (Corporativo)'),
('Fotógrafo (Produtos)'),
('Videomaker'),
('Produtor de Vídeo Publicitário'),
('Produtora de Áudio / Locutor'),
('Serviços Gráficos / Impressão'),
('Brindes Corporativos'),
('Uniformes Profissionais'),
('Serviços de Limpeza Comercial'),
('Serviços de Limpeza Residencial'),
('Dedetizadora'),
('Manutenção Predial'),
('Eletricista Instalador'),
('Bombeiro Hidráulico'),
('Marceneiro'),
('Serralheiro'),
('Vidraceiro'),
('Gesseiro / Drywall'),
('Pintor (Imóveis)'),
('Tapeceiro / Reformador de Estofados'),
('Ar Condicionado (Instalação e Manutenção)'),
('Segurança Eletrônica (Alarmes, Câmeras)'),
('Monitoramento de Alarmes'),
('Portaria Remota / Virtual'),
('Serviços de Segurança Patrimonial (Vigilantes)'),
('Recrutamento e Seleção'),
('Consultor de RH'),
('Treinamento Corporativo'),
('Consultor de Vendas'),
('Palestrante'),
('Cerimonialista / Organizador de Eventos'),
('Decoração de Eventos'),
('Buffet / Catering'),
('Locação de Equipamentos para Eventos'),
('Assessoria de Casamento'),
('Agência de Viagens (Corporativo)'),
('Agência de Viagens (Lazer)'),
('Turismo (Receptivo)'),
('Transporte Executivo'),
('Gráfica Rápida'),
('Encadernação / Acabamento Gráfico'),
('Suprimentos para Escritório'),
('Móveis para Escritório'),
('Equipamentos de Informática'),
('Suporte Técnico em Informática'),
('Desenvolvimento de Software (Sob Medida)'),
('Sistemas de Gestão Empresarial (ERP)'),
('Sistemas de CRM'),
('Automação Comercial'),
('Provedor de Internet'),
('Serviços de Telefonia / PABX'),
('Consultor de Telecomunicações'),
('Marketing Multinível / Vendas Diretas (especificar produto)'),
('Cosméticos / Produtos de Beleza (Venda Direta)'),
('Joias / Semijoias (Venda Direta)'),
('Produtos Nutricionais / Suplementos (Venda Direta)'),
('Artesanato / Produtos Personalizados'),
('Floricultura'),
('Presentes / Cestas Personalizadas'),
('Lavanderia (Comercial)'),
('Lavanderia (Residencial)'),
('Costureira / Alfaiate'),
('Sapataria / Conserto de Calçados'),
('Chaveiro'),
('Despachante (Veículos)'),
('Despachante (Imóveis)'),
('Tradutor / Intérprete'),
('Escola de Idiomas'),
('Reforço Escolar / Aulas Particulares'),
('Auto Escola'),
('Estúdio de Pilates'),
('Academia / Centro de Treinamento'),
('Estúdio de Dança'),
('Artes Marciais'),
('Salão de Beleza (Cabeleireiro)'),
('Salão de Beleza (Manicure/Pedicure)'),
('Esteticista'),
('Maquiador(a) Profissional'),
('Podólogo'),
('Massagista Terapêutico'),
('Serviços Funerários'),
('Cemitério / Crematório'),
('Pet Shop / Banho e Tosa'),
('Creche para Cães'),
('Adestrador de Cães'),
('Distribuidor de Bebidas'),
('Distribuidor de Alimentos'),
('Representante Comercial (diversos setores)'),
('Logística / Transportadora'),
('Despachante Aduaneiro'),
('Comércio Exterior / Importação e Exportação'),
('Agente Marítimo'),
('Corretor de Câmbio'),
('Franquias (Consultoria para Franquias)'),
('Consultor de Gestão Empresarial'),
('Consultor de Processos'),
('Consultor de Qualidade (ISO, etc.)'),
('Coach de Carreira'),
('Headhunter'),
('Consultor de Sustentabilidade'),
('Energia Solar (Instalação/Comercialização)'),
('Segurança do Trabalho (Consultoria)'),
('Medicina do Trabalho'),
('Ginástica Laboral'),
('Ergonomia (Consultoria)'),
('Comunicação Interna'),
('Endomarketing'),
('Pesquisa de Mercado'),
('Neuromarketing'),
('Trade Marketing'),
('Visual Merchandising'),
('Fotografia Aérea (Drone)'),
('Produção Musical / Estúdio'),
('DJ para Eventos'),
('Sonorização e Iluminação para Eventos'),
('Locação de Veículos'),
('Blindagem de Veículos'),
('Rastreamento Veicular'),
('Consórcio (Vendedor)'),
('Financiamento Imobiliário / Automotivo'),
('Câmbio de Moedas'),
('Joalheria / Ourives'),
('Relojoaria'),
('Ótica'),
('Loja de Roupas (Feminina)'),
('Loja de Roupas (Masculina)'),
('Loja de Roupas (Infantil)'),
('Loja de Calçados'),
('Loja de Bolsas e Acessórios'),
('Loja de Artigos Esportivos'),
('Bicicletaria'),
('Loja de Eletrônicos'),
('Assistência Técnica de Eletrônicos'),
('Loja de Informática'),
('Papelaria / Armarinho'),
('Loja de Brinquedos'),
('Loja de Decoração'),
('Loja de Presentes Criativos'),
('Loja de Produtos Naturais'),
('Empório / Produtos Gourmet'),
('Cafeteria'),
('Restaurante'),
('Pizzaria'),
('Hamburgueria'),
('Confeitaria / Doceria'),
('Padeiro / Fornecedor de Pães'),
('Serviços de Buffet Infantil'),
('Recreação Infantil para Eventos'),
('Locação de Brinquedos Infláveis'),
('Mágico / Recreador'),
('Serviço de Manobrista (Valet)'),
('Assessoria de Imprensa Pessoal (para Executivos)'),
('Consultor de Imagem e Estilo'),
('Personal Organizer'),
('Serviços de Cartório / Tabelionato (Representante)'),
('Leiloeiro'),
('Colecionador / Avaliador de Arte'),
('Restauração de Obras de Arte / Móveis Antigos'),
('Filatelista / Numismata'),
('Instrutor de Mergulho'),
('Escola de Vela / Esportes Náuticos'),
('Serviços de Outdoor / Mídia Exterior'),
('Mídia Indoor / Digital Signage'),
('Marketing Olfativo'),
('Musicoterapia'),
('Arteterapia'),
('Consultor de Feng Shui'),
('Radiestesia / Radiônica'),
('Terapias Holísticas (Reiki, Acupuntura, etc.)'),
('Aromaterapia'),
('Florais de Bach'),
('Quiroprata'),
('Acupunturista Veterinário'),
('Hotel para Cães / Gatos'),
('Serviço de Passeio com Cães (Dog Walker)'),
('Fotógrafo Pet'),
('Adestramento Comportamental Animal'),
('Zootecnista / Consultor em Criação Animal'),
('Agrônomo / Consultor Agrícola'),
('Veterinário Nutrólogo'),
('Fisioterapeuta Veterinário'),
('Acupunturista Humano'),
('Hipnoterapeuta'),
('Terapeuta de Regressão'),
('Constelação Familiar'),
('Instrutor de Yoga'),
('Instrutor de Meditação'),
('Coach Espiritual'),
('Numerólogo'),
('Astrólogo'),
('Tarólogo'),
('Consultor de Vinhos / Sommelier'),
('Mestre Cervejeiro / Cervejaria Artesanal'),
('Produtor de Queijos Artesanais'),
('Produtor de Doces / Geleias Artesanais');
